export const SUBJECT_CODES: Record<string, string> = {
	Accounting: 'ACCT',
	'Aerospace Engineering & Tech': 'AERO',
	'Agricultural Science': 'AGRI',
	'Animal Husbandry': 'ANIM',
	Anthropology: 'ANTH',
	Archaeology: 'ARCY',
	'Architecture & Urban Environmt': 'ARCH',
	'Artificial Intelligence': 'ARTI',
	'Banking and Finance': 'BAFI',
	'Biological Sciences': 'BIOL',
	'Building Construction Managemt': 'BLDG',
	'Business and Management': 'BUSI',
	Chemistry: 'CHEM',
	'Civil Engineering': 'ENGC',
	'Common Core': 'COREX',
	'Communication & Media Studies': 'COMM',
	'Computer Graphics': 'COGR',
	'Computer Science': 'COMP',
	'Creative Arts': 'CREA',
	Criminology: 'CRIM',
	Dentistry: 'DENT',
	'Earth Sciences': 'EART',
	'Ecology and Evolution': 'ECOL',
	Economics: 'ECON',
	Education: 'EDUC',
	'Electric/Electronic Eng & Tech': 'ENGE',
	'Engineering & Related Tech': 'ENGI',
	'Environmental Engineering': 'ENGVX',
	'Environmental Studies': 'ENVI',
	'Food Science and Biotechnology': 'FOOD',
	Geology: 'GEOL',
	'Graphic and Design Studies': 'GRAP',
	Health: 'HLTH',
	History: 'HIST',
	'Hospitality Management': 'HOSP',
	'Human Biology': 'HBIO',
	'Human Movement': 'HUMV',
	'Human Resource Management': 'HRES',
	'Indigenous Studies': 'INDG',
	'Information Systems': 'INFO',
	'Interior Architecture': 'INTE',
	'International Business': 'IBUS',
	Journalism: 'JOUR',
	'Language and Literature': 'LANG',
	Law: 'LAWS',
	'Librn\\shp,InfoMgmt & Curator S': 'LIBR',
	Linguistics: 'LING',
	Literature: 'LITR',
	'Mathematical Sciences': 'MATH',
	'Mechanical & Indust Eng & Tech': 'ENGM',
	Media: 'MDIA',
	'Medical Studies': 'MDST',
	Medicine: 'MEDI',
	Midwifery: 'MIDW',
	Music: 'MUSI',
	Nursing: 'NURS',
	Nutrition: 'NUTR',
	'Occupational Therapy': 'OCCU',
	'Other Natural & Physcl Science': 'SCIE',
	'Performing Arts': 'PERF',
	Pharmacy: 'PHAR',
	'Philosophy and Religious Studi': 'PHIL',
	'Physics and Astronomy': 'PHYS',
	Physiotherapy: 'PSIO',
	Podiatry: 'PODI',
	'Political Sci & Policy Studies': 'POLI',
	'Process & Resource Engineering': 'ENGP',
	'Project Management': 'PROJ',
	Psychology: 'PSYC',
	'Public Health': 'PUBH',
	Radiology: 'RADI',
	'Rehabilitation Therapies': 'REHB',
	Research: 'RESE',
	'Sales and Marketing': 'MARK',
	'Social Work': 'SOCW',
	Sociology: 'SOCI',
	'Speech Pathology': 'SPTH',
	'Sport and Recreation': 'SPOR',
	Statistics: 'STAT',
	'Veterinary Science': 'VETS',
	'Visual Arts and Crafts': 'VISU',
	'Viticulture & Oenology': 'WINE',
	'Written Communication': 'WRIT',
};
